version: '3.8'

services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=America/Argentina/Buenos_Aires

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
      args:
        VITE_API_URL=${VITE_API_URL}
        VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    restart: unless-stopped
    depends_on:
      - backend
